apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: knative-operator
  namespace: knative-operator
spec:
  interval: 10m
  chart:
    spec:
      chart: knative-operator
      version: "1.17.0" 
      sourceRef:
        kind: HelmRepository
        name: knative
        namespace: flux-system
  install:
    createNamespace: true
  upgrade:
    crds: CreateReplace
  values: {}

