apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster
  namespace: flux-system
spec:
  interval: 10m
  path: ./cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: lucca-k8s-datev
  validation: client
