apiVersion: sources.knative.dev/v1alpha1
kind: RabbitmqSource
metadata:
  name: datev-source
spec:
  rabbitmqClusterReference:
    # Configure name if a RabbitMQ Cluster Operator is being used.
    name: invoice-queue
  rabbitmqResourcesConfig:
    parallelism: 10
    exchangeName: "amq.headers"
    queueName: "my_new_queue"
  delivery:
    retry: 5
    backoffPolicy: "linear"
    backoffDelay: "PT1S"
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: generate-invoice
