apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init-script
data:
  init.js: |
    db = db.getSiblingDB('banksdb');
    db.bics.insertMany([
      { bic: "DEUTDEFF", bankName: "Deutsche Bank" },
      { bic: "CHASUS33", bankName: "JPMorgan Chase Bank" },
      { bic: "BARCGB22", bankName: "Barclays Bank" },
      { bic: "BNPAFRPP", bankName: "BNP Paribas" },
      { bic: "CITIGB2L", bankName: "Citibank London" },
      { bic: "IRVTUS3N", bankName: "Bank of New York Mellon" },
      { bic: "UBSWCHZH", bankName: "UBS Switzerland" },
      { bic: "HSBCHKHH", bankName: "HSBC Hong Kong" },
      { bic: "MIDLGB22", bankName: "HSBC UK" },
      { bic: "SOGEFRPP", bankName: "Societe Generale" }
    ]);