apiVersion: v1
kind: ConfigMap
metadata:
  name: config-observability
  namespace: knative-serving
data:
  metrics.backend-destination: "prometheus"
  metrics.request-metrics-backend-destination: "prometheus"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-observability
  namespace: knative-eventing
data:
  metrics.backend-destination: "prometheus"
  metrics.request-metrics-backend-destination: "prometheus"
