{
 "title": "Demo Dashboard",
 "time": { "from": "2024-11-25T11:02:07.670Z", "to": "2024-11-25T11:32:07.672Z" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "revision",
    "query": "generate-invoice,\ngenerate-invoice-final,"
   },
   { "name": "namespace", "query": "default,\ntesting" }
  ]
 },
 "panels": [
  { "title": "RabbitMQ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RabbitMQ Incoming Messages (5m)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(rabbitmq_global_messages_received_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unacknowledged messages",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_unacked * on(instance, job) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"invoice-queue\", namespace=\"default\"})"
    }
   ]
  },
  {
   "title": "RabbitMQ Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_connections * on(instance, job) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"invoice-queue\", namespace=\"default\"})"
    }
   ]
  },
  {
   "title": "Incoming messages / s",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_global_messages_received_total[60s]) * on(instance, job) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"invoice-queue\", namespace=\"default\"})"
    }
   ]
  },
  { "title": "Knative", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "generate-invoice Total CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"$revision.*\", container != \"POD\", container != \"\"}[120s])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "generate-invoice Total Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"default\", pod=~\"$revision.*\", container != \"POD\", container != \"\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Revision Pod Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(autoscaler_actual_pods{namespace_name=\"default\", configuration_name=\"generate-invoice\", revision_name=~\"$revision.*\"})",
     "legendFormat": "Actual Pods"
    },
    {
     "expr": "sum(autoscaler_requested_pods{namespace_name=\"default\", configuration_name=\"generate-invoice\", revision_name=~\"$revision.*\"})",
     "legendFormat": "Requested Pods"
    },
    {
     "expr": "sum(autoscaler_pending_pods{namespace_name=\"default\", configuration_name=\"generate-invoice\", revision_name=~\"$revision.*\"})",
     "legendFormat": "Pending Pods"
    },
    {
     "expr": "sum(autoscaler_not_ready_pods{namespace_name=\"default\", configuration_name=\"generate-invoice\", revision_name=~\"$revision.*\"})",
     "legendFormat": "NotReady Pods"
    },
    {
     "expr": "sum(autoscaler_terminating_pods{namespace_name=\"default\", configuration_name=\"generate-invoice\", revision_name=~\"$revision.*\"})",
     "legendFormat": "Terminating Pods"
    }
   ]
  },
  {
   "title": "Median and Tail Latency",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5,sum by (le) (rate(activator_request_latencies_bucket{service_name=\"generate-invoice\"}[90s])))",
     "legendFormat": "Median"
    },
    {
     "expr": "histogram_quantile(0.95,sum by (le) (rate(activator_request_latencies_bucket{service_name=\"generate-invoice\"}[90s])))",
     "legendFormat": "Tail (p95)"
    }
   ]
  },
  {
   "title": "Success Rate (non-5xx responses)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(activator_request_count{response_code_class!=\"5xx\", namespace_name=\"$namespace\", revision_name=~\"$revision\", configuration_name=~\"generate-invoice-final\"}[90s])) / sum(rate(activator_request_count{namespace_name=\"$namespace\", revision_name=~\"$revision\", configuration_name=~\"generate-invoice-final\"}[90s]))"
    }
   ]
  }
 ]
}